### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by BenSpex** [sssssyf/SF-ESMF#1]
Hi Yifan Sun, 
@sssssyf 

just wanted to know if you are planing to release the code? 
And if not if there is a possibility to get access to the paper? 

Thanks
Ben

**Comment by sssssyf** [comment]
I will release the code as quickly as possible，no more than a week.

**Comment by sssssyf** [comment]
> Hi Yifan Sun, @sssssyf
> 
> just wanted to know if you are planing to release the code? And if not if there is a possibility to get access to the paper?
> 
> Thanks Ben

I will release the code as quickly as possible，no more than a week.

**Comment by BenSpex** [comment]
Ah great awesome, thanks for the quick reply.
